version: "3.3"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33060:3306
    volumes:
      - ./docker/mysql:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/data:/data/db
    command: --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      TZ: "Asia/Shanghai"